# Generated by Django 2.1.7 on 2019-04-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateField()),
                ('photo_main', models.CharField(max_length=128)),
                ('photo_1', models.CharField(max_length=128)),
                ('photo_2', models.CharField(max_length=128)),
                ('photo_3', models.CharField(max_length=128)),
                ('photo_4', models.CharField(max_length=128)),
                ('photo_5', models.CharField(max_length=128)),
                ('photo_6', models.CharField(max_length=128)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor')),
            ],
        ),
    ]
