# Generated by Django 2.1.7 on 2019-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
