# Generated by Django 2.1.7 on 2019-04-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20190401_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 1, 12, 35, 33, 624344)),
        ),
    ]
